---
title: "Feature selection with STIR"
output: html_document
---

```{r}
library(tidyverse)
library(vroom)
library(npdr)

set.seed(1618)
```

```{r}
datasets <- read_csv('qsar_datasets.txt', col_names = F) %>% pull()

datasets <- datasets[7]
```


```{r}
# dataset = datasets[1]
for (dataset in datasets){
  metab <- paste0('qsar/', dataset, '_training_preprocessed.csv') %>%
    vroom() %>%
    dplyr::select(- MOLECULE) %>%
    data.frame()
  
  system.time(
    npdr.metab.results <-
      npdr('Act', metab, regression.type='lm',
           attr.diff.type = 'numeric-abs', nbd.method = 'multisurf',
           nbd.metric = 'manhattan', msurf.sd.frac = .5,
           padj.method = 'bonferroni', verbose = T)
  )
  
  npdr_feats <- npdr.metab.results %>%
    filter(pval.adj < 0.05) %>%
    pull(att)
  
  metab %>%
    dplyr::select('Act', npdr_feats) %>%
    write_csv(paste0('qsar_npdr/', dataset, '_training_npdr.csv'))
  
  save(npdr.metab.results, file = paste0('results/', dataset, '_training_npdr.Rdata'))
}

```

